Update version url pattern and introduce backwards-compatible fetching
greymatter-io/gmenv pull request #25
Opened 2020-12-07 17:04 UTC by jack-bischoff

Closes #24 

New artifacts are built and pushed to Nexus without a v prefix (e.g. `2.0.0` instead of `v2.0.0`). This causes gmenv to fail when fetching newer artifacts.

This PR addresses the above issue by setting the default url to a non-v-prefixed scheme and then allowing for a fallback on a v-prefix version format url if curl encounters a 404. If the fallback still fails, then the tool will still output a critical error and exit.

2020-12-07 17:17 UTC, kaitmore requested changes
Works great, nice job Jack! Would you mind adding a test case for this?

2020-12-07 18:30 UTC, chrisbsmith commented on libexec/gmenv-install
> +response=$(curlw -u ${credentials} ${curl_progress} -f -o "${download_tmp}" "${version_url}")
You are setting this to `responses` but never using `responses`. You should be able to execute this command without needing to set the output to a value.

2020-12-07 18:37 UTC, chrisbsmith commented
@jack-bischoff this is good.  I'd like to discuss my comment with you when ready.

There's a little bit of trickery needed to actually release this.  Follow the below steps to trigger the release.

- Once this PR is merged, create a new branch called `release-0.3.3`
- update `.release` with today's date
- commit and submit a new PR
- upon merge, this will tigger the changelog-ci and the github actions to release to our brew repo

2020-12-07 18:47 UTC, jack-bischoff commented on libexec/gmenv-install
> +response=$(curlw -u ${credentials} ${curl_progress} -f -o "${download_tmp}" "${version_url}")
Fixed!

2020-12-07 19:11 UTC, chrisbsmith commented on test/test_install_and_use.sh
> +  '1.0.1,1.0.1'
can you explore adding a negative test case as well?  Just down in this file. Search for `neg_tests__kv`

2020-12-07 19:36 UTC, jack-bischoff commented on test/test_install_and_use.sh
> +  '1.0.1,1.0.1'
I can yes, I'm not sure how to accomplish that though. If X.Y.Z isn't found, it will curl vX.Y.Z which if that isn't found will fail. But since the version is checked before curling the url, then either X.Y.Z or vX.Y.Z should always resolve to an artifact, right?

I think my first test case should actually be  2.0.0 since it doesn't include the v prefix, whereas the other versions listed in the tests do include the v prefix.

2020-12-07 19:45 UTC, chrisbsmith commented on test/test_install_and_use.sh
> +  '1.0.1,1.0.1'
Fair enough.  The positive test should be sufficient.

2020-12-07 20:59 UTC, chrisbsmith commented
@jack-bischoff i just realized i have an error in the test workflow.  Can you look at this line and see what it'll take to checkout the current branch rather than master.  doesn't do much good to checkout master all the time. oops :/

https://github.com/greymatter-io/gmenv/blob/6028bd36c24c18dd7d298b3a87e8f7e57f3a90d6/.github/workflows/test.yaml#L12

2020-12-08 15:37 UTC, jack-bischoff commented
> @jack-bischoff i just realized i have an error in the test workflow. Can you look at this line and see what it'll take to checkout the current branch rather than master. doesn't do much good to checkout master all the time. oops :/
> 
> https://github.com/greymatter-io/gmenv/blob/6028bd36c24c18dd7d298b3a87e8f7e57f3a90d6/.github/workflows/test.yaml#L12
I think this is actually not an issue...

After looking into the docs for actions/checkout and examining the logs, I think this command is actually referring to the master branch of the actions/checkout repo, rather than the gmenv repo, since a git fetch to the fix-v-prefix branch does occur. However, I went ahead and updated the branch to the v2 tag, which is recommended.

2020-12-08 15:40 UTC, chrisbsmith approved these changes
LGTM

Something's up with the tests, but I can see the fallback to the `v` working.

2020-12-08 17:24 UTC, jack-bischoff commented
There was a small increment error that was skipping tests, now they should look normal. 

A side effect of this is that the 2.0.0 cli "fails" on the `check_installed_version` function because it no longer contains the `--version` flag.

2020-12-08 17:31 UTC, chrisbsmith commented on test/test_install_and_use.sh
> -  test_num+=1;
Nice catch!

2020-12-08 17:36 UTC, jack-bischoff commented on test/test_install_and_use.sh
> -  test_num+=1;
thanks!

2020-12-08 17:39 UTC, jack-bischoff commented
@chrisbsmith 

The second (`'latest possibly-unstable version'`) .greymatter-version test is failing, probably because it is trying to download 1.4.2 but is downloading 0.1.0 instead:
```
## ./.greymatter-version Test 1/5: latest possibly-unstable version ( 1.4.2: / 1.4.2 )
Writing 1.4.2: to ./.greymatter-version
Installing Grey Matter v0.1.0
Downloading release tarball from https://nexus.greymatter.io/repository/raw/release/gm-cli/greymatter-0.1.0.tar.gz
############################################################################################################# 100.0%

Installation of greymatter v0.1.0 successful. To make this your default version, run 'gmenv use 0.1.0'
/Users/jackbischoff/Code/gmenv/lib/helpers.sh: line 114: /Users/jackbischoff/Code/gmenv/versions/1.4.2/greymatter: No such file or directory
```

The first test successfully downloads 1.4.2. The only difference between the two is the input, specifically, the first test's value is `1.4.2` whereas the second test's value is `1.4.2:`. Is that extra colon supposed to be there or could that be the culprit?

2020-12-08 17:41 UTC, chrisbsmith commented
Nice catch on the extra increment.

Well this is a real bummer about the version.  These are the lines that are breaking.

https://github.com/greymatter-io/gmenv/blob/6028bd36c24c18dd7d298b3a87e8f7e57f3a90d6/lib/helpers.sh#L105-L116

You could add a `$?` check after the `greymatter --version` call, and if it's `1`, then execute `greymatter version` with the same commands.  I think that would work

2020-12-08 17:43 UTC, chrisbsmith commented
> @chrisbsmith
> 
> The second (`'latest possibly-unstable version'`) .greymatter-version test is failing, probably because it is trying to download 1.4.2 but is downloading 0.1.0 instead:
> 
> ```
> ## ./.greymatter-version Test 1/5: latest possibly-unstable version ( 1.4.2: / 1.4.2 )
> Writing 1.4.2: to ./.greymatter-version
> Installing Grey Matter v0.1.0
> Downloading release tarball from https://nexus.greymatter.io/repository/raw/release/gm-cli/greymatter-0.1.0.tar.gz
> ############################################################################################################# 100.0%
> 
> Installation of greymatter v0.1.0 successful. To make this your default version, run 'gmenv use 0.1.0'
> /Users/jackbischoff/Code/gmenv/lib/helpers.sh: line 114: /Users/jackbischoff/Code/gmenv/versions/1.4.2/greymatter: No such file or directory
> ```
> 
> The first test successfully downloads 1.4.2. The only difference between the two is the input, specifically, the first test's value is `1.4.2` whereas the second test's value is `1.4.2:`. Is that extra colon supposed to be there or could that be the culprit?
> 
> Here is the full key-value paring:
> 
> ```
> tests__kv=(
>   "$(gmenv list-remote | grep -e "^[0-9]\+\.[0-9]\+\.[0-9]\+$" | tail -n 1),1.4.2"
>   "$(gmenv list-remote | tail -n 1),1.4.2:"
>   '1.4.1,latest:^1.4'
>   '2.0.0,2.0.0'
>   '1.0.1,1.0.1'
> )
> ```

This must be a bad hangover from when I stole this from `tfenv`.  We don't have any possibly-unstable versions so you can remove the test all together.  Good catch!

2020-12-08 19:00 UTC, chrisbsmith commented on lib/helpers.sh
> +  [ -n "$(${bin} version | grep -E "^ Version: \s*v${v}((-dev)|( \([a-f0-9]+\)))?$") | head -1" ];
Do older versions of `greymatter` also support `version` without the `--`?

2020-12-08 19:00 UTC, merged

2020-12-08 19:01 UTC, jack-bischoff commented on lib/helpers.sh
> +  [ -n "$(${bin} version | grep -E "^ Version: \s*v${v}((-dev)|( \([a-f0-9]+\)))?$") | head -1" ];
Yes, I went through them starting at 0.1.0 and they all seem to support it even thought they do not explicitly state it

2020-12-08 19:33 UTC, chrisbsmith commented
@jack-bischoff just a reminder to cut a release with a new branch name.  

* Once this PR is merged, create a new branch called release-0.3.3
* update .release with today's date
* commit and submit a new PR
* upon merge, this will tigger the changelog-ci and the github actions to release to our brew repo